# Generated by Django 5.1.3 on 2024-12-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_captain_phone_number_client_phone_number"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="client_permissions", to="auth.permission"
            ),
        ),
    ]
