# Generated by Django 4.2.17 on 2024-12-26 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_client_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('country_code', models.CharField(default='+20', max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_app_client_profile', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='CaptainProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('country_code', models.CharField(default='+20', max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('captain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_app_captain_profile', to='accounts.captain')),
            ],
        ),
    ]
