# Generated by Django 4.2.17 on 2024-12-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_client_user_permissions'),
        ('profile_app', '0003_alter_profile_captain_alter_profile_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='captain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_app_captain', to='accounts.captain'),
        ),
    ]
