# Generated by Django 4.2.17 on 2024-12-29 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_client_user_permissions'),
        ('profile_app', '0005_alter_profile_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('captain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captain_profile', to='accounts.captain')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='accounts.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
