# Generated by Django 4.2.17 on 2024-12-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_captainprofile_clientprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captainprofile',
            name='country_code',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='country_code',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
