# Generated by Django 5.1.3 on 2024-12-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("orders", "Orders"), ("news_feed", "News Feed")],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("user_name", models.CharField(max_length=100)),
                ("profile_picture_url", models.CharField(max_length=250)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
